### ISSUE TITLE
Scheduler | Verify Button

### ISSUE THREAD

**Issue by mwekis** [umkc-cs-451-2020-spring/semester-project-group-11#8]
How do we want to represent constraints?  I propose a pop up window that lists constraints when we opt to save the schedule.

**Comment by nextofblake** [comment]
Action: @click button
Method: verify()
- this should run the scheduler verification
- save the output to the schedulers data
 
data() {
  return {
     verificationReturnDataVariable: null
  }
},

methods: {
   verify() {
       this.verificationReturnDataVariable = schedule.verificationMethod()
   }
}
